name: polyline
description: Polyline encoding algorithm for encoding and decoding a list of coordinates
version: 1.1.0
homepage: https://github.com/sashvoncurtis/polyline.dart
author: sashnortier <sashnortier@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
